"""empty message

Revision ID: 103c3a97c406
Revises: 0fb285c4dbd4
Create Date: 2019-09-07 14:01:09.474130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103c3a97c406'
down_revision = '0fb285c4dbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('links', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'links', 'link_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_column('links', 'category_id')
    op.drop_table('link_category')
    # ### end Alembic commands ###
